*
*  Source machine generated by GadToolsBox V2.0
*  which is (c) Copyright 1991-1993 Jaba Development
*
*  GUI Designed by : Nicholas Harvey
*

    XREF    _GadToolsBase
    XREF    _IntuitionBase
    XREF    _GfxBase
    XREF    _SysBase
    XREF    _UtilityBase

OpenScreenTagList    EQU    -612
OpenWindowTagList    EQU    -606
CloseScreen          EQU    -66
CloseWindow          EQU    -72
PrintIText           EQU    -216
LockPubScreen        EQU    -510
UnlockPubScreen      EQU    -516
SetMenuStrip         EQU    -264
ClearMenuStrip       EQU    -54
GetVisualInfoA       EQU    -126
FreeVisualInfo       EQU    -132
CreateContext        EQU    -114
CreateGadgetA        EQU    -30
GT_RefreshWindow     EQU    -84
FreeGadgets          EQU    -36
CreateMenusA         EQU    -48
LayoutMenusA         EQU    -66
FreeMenus            EQU    -54
OpenDiskFont         EQU    -30
CloseFont            EQU    -78
DrawBevelBoxA        EQU    -120
FreeClass            EQU    -714
NewObjectA           EQU    -636
DisposeObject        EQU    -642
TextLength           EQU    -54
CopyMem              EQU    -624
FindTagItem          EQU    -30
IntuiTextLength      EQU    -330
Forbid               EQU    -132
Permit               EQU    -138

GD_PPOKButton                          EQU    0
GD_PPCancelButton                      EQU    1
GD_PPNLQCheck                          EQU    2
GD_PPProportionalCheck                 EQU    3
GD_PPDoubleSpaceCheck                  EQU    4
GD_PPTopMarginStr                      EQU    5
GD_PPBottomMarginStr                   EQU    6
GD_PPPageLengthStr                     EQU    7
GD_PPLeftMarginStr                     EQU    8
GD_PPRightMarginStr                    EQU    9
GD_PPPageWidthStr                      EQU    10
GD_PPPrintToStr                        EQU    11
GD_PPNumCopiesStr                      EQU    12

GD_ColoursTextGad                      EQU    0
GD_ColoursFieldGad                     EQU    1
GD_ColoursOKGad                        EQU    2
GD_ColoursCancelGad                    EQU    3

GD_FuncKeysOKGad                       EQU    0
GD_FuncKeysCancelGad                   EQU    1
GD_FuncKeysF1Gad                       EQU    2
GD_FuncKeysF2Gad                       EQU    3
GD_FuncKeysF3Gad                       EQU    4
GD_FuncKeysF4Gad                       EQU    5
GD_FuncKeysF5Gad                       EQU    6
GD_FuncKeysF6Gad                       EQU    7
GD_FuncKeysF7Gad                       EQU    8
GD_FuncKeysF8Gad                       EQU    9
GD_FuncKeysF9Gad                       EQU    10
GD_FuncKeysF10Gad                      EQU    11

GD_PrintedPercentageCancel             EQU    0
GD_PrintedPercentageNum                EQU    1

GD_SpellSuggestionsGad                 EQU    0
GD_SpellReplaceGad                     EQU    1
GD_SpellUnknownGad                     EQU    2
GD_SpellCheckIgnoreGad                 EQU    3
GD_SpellCheckCancelGad                 EQU    4
GD_SpellCheckLearnGad                  EQU    5
GD_SpellCheckReplaceGad                EQU    6

GD_FindOKGad                           EQU    0
GD_FindCancelGad                       EQU    1
GD_ReplaceStringGad                    EQU    2
GD_FindStringGad                       EQU    3

PrinterPrefs_CNT    EQU    13
Colours_CNT    EQU    4
FunctionKeys_CNT    EQU    12
PrintDocument_CNT    EQU    2
SpellChecker_CNT    EQU    7
FindText_CNT    EQU    4

    XDEF    Scr
    XDEF    VisualInfo
    XDEF    PubScreenName
    XDEF    MainEditWindowWnd
    XDEF    PrinterPrefsWnd
    XDEF    ColoursWnd
    XDEF    FunctionKeysWnd
    XDEF    PrintDocumentWnd
    XDEF    SpellCheckerWnd
    XDEF    FindTextWnd
    XDEF    PrinterPrefsGList
    XDEF    ColoursGList
    XDEF    FunctionKeysGList
    XDEF    PrintDocumentGList
    XDEF    SpellCheckerGList
    XDEF    FindTextGList
    XDEF    MainEditWindowMenus
    XDEF    PrinterPrefsGadgets
    XDEF    ColoursGadgets
    XDEF    FunctionKeysGadgets
    XDEF    PrintDocumentGadgets
    XDEF    SpellCheckerGadgets
    XDEF    FindTextGadgets
    XDEF    MainEditWindowLeft
    XDEF    MainEditWindowTop
    XDEF    MainEditWindowWidth
    XDEF    MainEditWindowHeight
    XDEF    PrinterPrefsLeft
    XDEF    PrinterPrefsTop
    XDEF    PrinterPrefsWidth
    XDEF    PrinterPrefsHeight
    XDEF    ColoursLeft
    XDEF    ColoursTop
    XDEF    ColoursWidth
    XDEF    ColoursHeight
    XDEF    FunctionKeysLeft
    XDEF    FunctionKeysTop
    XDEF    FunctionKeysWidth
    XDEF    FunctionKeysHeight
    XDEF    PrintDocumentLeft
    XDEF    PrintDocumentTop
    XDEF    PrintDocumentWidth
    XDEF    PrintDocumentHeight
    XDEF    SpellCheckerLeft
    XDEF    SpellCheckerTop
    XDEF    SpellCheckerWidth
    XDEF    SpellCheckerHeight
    XDEF    FindTextLeft
    XDEF    FindTextTop
    XDEF    FindTextWidth
    XDEF    FindTextHeight
    XDEF    Font
    XDEF    Attr
    XDEF    FontX
    XDEF    FontY
    XDEF    OffX
    XDEF    OffY

Scr:
    DC.L    0
VisualInfo:
    DC.L    0
PubScreenName:
    DC.L    WBName
WBName:
    DC.B    'Workbench',0
    CNOP  0,2
MainEditWindowWnd:
    DC.L    0
PrinterPrefsWnd:
    DC.L    0
ColoursWnd:
    DC.L    0
FunctionKeysWnd:
    DC.L    0
PrintDocumentWnd:
    DC.L    0
SpellCheckerWnd:
    DC.L    0
FindTextWnd:
    DC.L    0
PrinterPrefsGList:
    DC.L    0
ColoursGList:
    DC.L    0
FunctionKeysGList:
    DC.L    0
PrintDocumentGList:
    DC.L    0
SpellCheckerGList:
    DC.L    0
FindTextGList:
    DC.L    0
MainEditWindowMenus:
    DC.L    0
MTags0:
    DC.L    $80080032,0,$00000000
MTags1:
    DC.L    $80080043,1
    DC.L    $00000000
PrinterPrefsGadgets:
    DCB.L    13,0
ColoursGadgets:
    DCB.L    4,0
FunctionKeysGadgets:
    DCB.L    12,0
PrintDocumentGadgets:
    DCB.L    2,0
SpellCheckerGadgets:
    DCB.L    7,0
FindTextGadgets:
    DCB.L    4,0
BufNewGad:
    DC.W    0,0,0,0
    DC.L    0,0
    DC.W    0
    DC.L    0,0,0
TD:
    DC.L    $00000000
NR:
    DC.L    $80080034,$00000000,$00000000
IR:
    DC.L    $80080034,$00000000,$80080033,1,$00000000
MainEditWindowLeft:
    DC.W    0
MainEditWindowTop:
    DC.W    11
MainEditWindowWidth:
    DC.W    632
MainEditWindowHeight:
    DC.W    232
PrinterPrefsLeft:
    DC.W    30
PrinterPrefsTop:
    DC.W    20
PrinterPrefsWidth:
    DC.W    444
PrinterPrefsHeight:
    DC.W    129
ColoursLeft:
    DC.W    30
ColoursTop:
    DC.W    20
ColoursWidth:
    DC.W    392
ColoursHeight:
    DC.W    84
FunctionKeysLeft:
    DC.W    30
FunctionKeysTop:
    DC.W    20
FunctionKeysWidth:
    DC.W    313
FunctionKeysHeight:
    DC.W    196
PrintDocumentLeft:
    DC.W    30
PrintDocumentTop:
    DC.W    20
PrintDocumentWidth:
    DC.W    165
PrintDocumentHeight:
    DC.W    48
SpellCheckerLeft:
    DC.W    30
SpellCheckerTop:
    DC.W    20
SpellCheckerWidth:
    DC.W    329
SpellCheckerHeight:
    DC.W    131
FindTextLeft:
    DC.W    30
FindTextTop:
    DC.W    20
FindTextWidth:
    DC.W    381
FindTextHeight:
    DC.W    69
Font:
    DC.L    0
FontX:
    DC.W    0
FontY:
    DC.W    0
OffX:
    DC.W    0
OffY:
    DC.W    0
Attr:
    DC.L    0
    DC.W    0
    DC.B    0,0
TopazName:
    DC.B    'topaz.font',0
    CNOP    0,2

MainEditWindowGTypes:

PrinterPrefsGTypes:
    DC.W    1
    DC.W    1
    DC.W    2
    DC.W    2
    DC.W    2
    DC.W    3
    DC.W    3
    DC.W    3
    DC.W    3
    DC.W    3
    DC.W    3
    DC.W    12
    DC.W    3

ColoursGTypes:
    DC.W    8
    DC.W    8
    DC.W    1
    DC.W    1

FunctionKeysGTypes:
    DC.W    1
    DC.W    1
    DC.W    12
    DC.W    12
    DC.W    12
    DC.W    12
    DC.W    12
    DC.W    12
    DC.W    12
    DC.W    12
    DC.W    12
    DC.W    12

PrintDocumentGTypes:
    DC.W    1
    DC.W    6

SpellCheckerGTypes:
    DC.W    4
    DC.W    12
    DC.W    13
    DC.W    1
    DC.W    1
    DC.W    1
    DC.W    1

FindTextGTypes:
    DC.W    1
    DC.W    1
    DC.W    12
    DC.W    12

MainEditWindowNGads:

PrinterPrefsNGads:
    DC.W    8,112,65,14
    DC.L    PPOKButtonText,0
    DC.W    GD_PPOKButton
    DC.L    $0010,0,0
    DC.W    371,112,65,14
    DC.L    PPCancelButtonText,0
    DC.W    GD_PPCancelButton
    DC.L    $0010,0,0
    DC.W    398,45,26,11
    DC.L    PPNLQCheckText,0
    DC.W    GD_PPNLQCheck
    DC.L    $0001,0,0
    DC.W    398,58,26,11
    DC.L    PPProportionalCheckText,0
    DC.W    GD_PPProportionalCheck
    DC.L    $0001,0,0
    DC.W    398,71,26,11
    DC.L    PPDoubleSpaceCheckText,0
    DC.W    GD_PPDoubleSpaceCheck
    DC.L    $0001,0,0
    DC.W    145,10,45,14
    DC.L    PPTopMarginStrText,0
    DC.W    GD_PPTopMarginStr
    DC.L    $0001,0,0
    DC.W    145,26,45,14
    DC.L    PPBottomMarginStrText,0
    DC.W    GD_PPBottomMarginStr
    DC.L    $0001,0,0
    DC.W    145,42,45,14
    DC.L    PPPageLengthStrText,0
    DC.W    GD_PPPageLengthStr
    DC.L    $0001,0,0
    DC.W    145,58,45,14
    DC.L    PPLeftMarginStrText,0
    DC.W    GD_PPLeftMarginStr
    DC.L    $0001,0,0
    DC.W    145,74,45,14
    DC.L    PPRightMarginStrText,0
    DC.W    GD_PPRightMarginStr
    DC.L    $0001,0,0
    DC.W    145,90,45,14
    DC.L    PPPageWidthStrText,0
    DC.W    GD_PPPageWidthStr
    DC.L    $0001,0,0
    DC.W    230,20,189,14
    DC.L    PPPrintToStrText,0
    DC.W    GD_PPPrintToStr
    DC.L    $0004,0,0
    DC.W    381,92,45,14
    DC.L    PPNumCopiesStrText,0
    DC.W    GD_PPNumCopiesStr
    DC.L    $0001,0,0

ColoursNGads:
    DC.W    21,23,161,33
    DC.L    ColoursTextGadText,0
    DC.W    GD_ColoursTextGad
    DC.L    $0004,0,0
    DC.W    211,23,161,33
    DC.L    ColoursFieldGadText,0
    DC.W    GD_ColoursFieldGad
    DC.L    $0004,0,0
    DC.W    8,67,65,14
    DC.L    ColoursOKGadText,0
    DC.W    GD_ColoursOKGad
    DC.L    $0010,0,0
    DC.W    319,67,65,14
    DC.L    ColoursCancelGadText,0
    DC.W    GD_ColoursCancelGad
    DC.L    $0010,0,0

FunctionKeysNGads:
    DC.W    8,179,65,14
    DC.L    FuncKeysOKGadText,0
    DC.W    GD_FuncKeysOKGad
    DC.L    $0010,0,0
    DC.W    240,179,65,14
    DC.L    FuncKeysCancelGadText,0
    DC.W    GD_FuncKeysCancelGad
    DC.L    $0010,0,0
    DC.W    62,11,229,14
    DC.L    FuncKeysF1GadText,0
    DC.W    GD_FuncKeysF1Gad
    DC.L    $0001,0,0
    DC.W    62,27,229,14
    DC.L    FuncKeysF2GadText,0
    DC.W    GD_FuncKeysF2Gad
    DC.L    $0001,0,0
    DC.W    62,43,229,14
    DC.L    FuncKeysF3GadText,0
    DC.W    GD_FuncKeysF3Gad
    DC.L    $0001,0,0
    DC.W    62,59,229,14
    DC.L    FuncKeysF4GadText,0
    DC.W    GD_FuncKeysF4Gad
    DC.L    $0001,0,0
    DC.W    62,75,229,14
    DC.L    FuncKeysF5GadText,0
    DC.W    GD_FuncKeysF5Gad
    DC.L    $0001,0,0
    DC.W    62,91,229,14
    DC.L    FuncKeysF6GadText,0
    DC.W    GD_FuncKeysF6Gad
    DC.L    $0001,0,0
    DC.W    62,107,229,14
    DC.L    FuncKeysF7GadText,0
    DC.W    GD_FuncKeysF7Gad
    DC.L    $0001,0,0
    DC.W    62,123,229,14
    DC.L    FuncKeysF8GadText,0
    DC.W    GD_FuncKeysF8Gad
    DC.L    $0001,0,0
    DC.W    62,139,229,14
    DC.L    FuncKeysF9GadText,0
    DC.W    GD_FuncKeysF9Gad
    DC.L    $0001,0,0
    DC.W    62,155,229,14
    DC.L    FuncKeysF10GadText,0
    DC.W    GD_FuncKeysF10Gad
    DC.L    $0001,0,0

PrintDocumentNGads:
    DC.W    48,31,65,14
    DC.L    PrintedPercentageCancelText,0
    DC.W    GD_PrintedPercentageCancel
    DC.L    $0010,0,0
    DC.W    117,10,32,13
    DC.L    PrintedPercentageNumText,0
    DC.W    GD_PrintedPercentageNum
    DC.L    $0001,0,0

SpellCheckerNGads:
    DC.W    128,38,184,72
    DC.L    SpellSuggestionsGadText,0
    DC.W    GD_SpellSuggestionsGad
    DC.L    $0001,0,0
    DC.W    128,23,184,14
    DC.L    SpellReplaceGadText,0
    DC.W    GD_SpellReplaceGad
    DC.L    $0001,0,0
    DC.W    128,10,184,12
    DC.L    SpellUnknownGadText,0
    DC.W    GD_SpellUnknownGad
    DC.L    $0001,0,0
    DC.W    8,114,65,14
    DC.L    SpellCheckIgnoreGadText,0
    DC.W    GD_SpellCheckIgnoreGad
    DC.L    $0010,0,0
    DC.W    256,114,65,14
    DC.L    SpellCheckCancelGadText,0
    DC.W    GD_SpellCheckCancelGad
    DC.L    $0010,0,0
    DC.W    173,114,65,14
    DC.L    SpellCheckLearnGadText,0
    DC.W    GD_SpellCheckLearnGad
    DC.L    $0010,0,0
    DC.W    90,114,65,14
    DC.L    SpellCheckReplaceGadText,0
    DC.W    GD_SpellCheckReplaceGad
    DC.L    $0010,0,0

FindTextNGads:
    DC.W    8,52,65,14
    DC.L    FindOKGadText,0
    DC.W    GD_FindOKGad
    DC.L    $0010,0,0
    DC.W    309,52,65,14
    DC.L    FindCancelGadText,0
    DC.W    GD_FindCancelGad
    DC.L    $0010,0,0
    DC.W    133,28,229,14
    DC.L    ReplaceStringGadText,0
    DC.W    GD_ReplaceStringGad
    DC.L    $0001,0,0
    DC.W    133,12,229,14
    DC.L    FindStringGadText,0
    DC.W    GD_FindStringGad
    DC.L    $0001,0,0

MainEditWindowGTags:


PrinterPrefsGTags:
    DC.L    $00000000
    DC.L    $00000000
    DC.L    $80080004,1
    DC.L    $00000000
    DC.L    $80080004,1
    DC.L    $00000000
    DC.L    $80080004,1
    DC.L    $00000000
    DC.L    $8008002F,0
    DC.L    $80080030,3
    DC.L    $00000000
    DC.L    $8008002F,0
    DC.L    $80080030,3
    DC.L    $00000000
    DC.L    $8008002F,0
    DC.L    $80080030,3
    DC.L    $00000000
    DC.L    $8008002F,0
    DC.L    $80080030,3
    DC.L    $00000000
    DC.L    $8008002F,0
    DC.L    $80080030,3
    DC.L    $00000000
    DC.L    $8008002F,0
    DC.L    $80080030,3
    DC.L    $00000000
    DC.L    $8008002D,PPPrintToStrString
    DC.L    $8008002E,256
    DC.L    $00000000
    DC.L    $8008002F,0
    DC.L    $80080030,3
    DC.L    $00000000


PPPrintToStrString:
    DC.B    'PRT:',0
    CNOP    0,2

ColoursGTags:
    DC.L    $80080010,1
    DC.L    $80080013,10
    DC.L    $80080011,0
    DC.L    $80080012,0
    DC.L    $00000000
    DC.L    $80080010,1
    DC.L    $80080013,10
    DC.L    $80080011,1
    DC.L    $80080012,0
    DC.L    $00000000
    DC.L    $00000000
    DC.L    $00000000


FunctionKeysGTags:
    DC.L    $00000000
    DC.L    $00000000
    DC.L    $8008002D,FuncKeysF1GadString
    DC.L    $8008002E,256
    DC.L    $00000000
    DC.L    $8008002D,FuncKeysF2GadString
    DC.L    $8008002E,256
    DC.L    $00000000
    DC.L    $8008002D,FuncKeysF3GadString
    DC.L    $8008002E,256
    DC.L    $00000000
    DC.L    $8008002D,FuncKeysF4GadString
    DC.L    $8008002E,256
    DC.L    $00000000
    DC.L    $8008002D,FuncKeysF5GadString
    DC.L    $8008002E,256
    DC.L    $00000000
    DC.L    $8008002D,FuncKeysF6GadString
    DC.L    $8008002E,256
    DC.L    $00000000
    DC.L    $8008002D,FuncKeysF7GadString
    DC.L    $8008002E,256
    DC.L    $00000000
    DC.L    $8008002D,FuncKeysF8GadString
    DC.L    $8008002E,256
    DC.L    $00000000
    DC.L    $8008002D,FuncKeysF9GadString
    DC.L    $8008002E,256
    DC.L    $00000000
    DC.L    $8008002D,FuncKeysF10GadString
    DC.L    $8008002E,256
    DC.L    $00000000


FuncKeysF1GadString:
    DC.B    '1',0
    CNOP    0,2

FuncKeysF2GadString:
    DC.B    '2',0
    CNOP    0,2

FuncKeysF3GadString:
    DC.B    '3',0
    CNOP    0,2

FuncKeysF4GadString:
    DC.B    '4',0
    CNOP    0,2

FuncKeysF5GadString:
    DC.B    '5',0
    CNOP    0,2

FuncKeysF6GadString:
    DC.B    '6',0
    CNOP    0,2

FuncKeysF7GadString:
    DC.B    '7',0
    CNOP    0,2

FuncKeysF8GadString:
    DC.B    '8',0
    CNOP    0,2

FuncKeysF9GadString:
    DC.B    '9',0
    CNOP    0,2

FuncKeysF10GadString:
    DC.B    '0',0
    CNOP    0,2

PrintDocumentGTags:
    DC.L    $00000000
    DC.L    $8008000D,0
    DC.L    $00000000


SpellCheckerGTags:
    DC.L    $80080006,0
    DC.L    $80080035,0
    DC.L    $00000000
    DC.L    $80030024,0
    DC.L    $8008002D,SpellReplaceGadString
    DC.L    $8008002E,256
    DC.L    $00000000
    DC.L    $8008000B,SpellUnknownGadString
    DC.L    $80080039,1
    DC.L    $00000000
    DC.L    $00000000
    DC.L    $00000000
    DC.L    $00000000
    DC.L    $00000000


SpellReplaceGadString:
    DC.B    'R',0
    CNOP    0,2

SpellUnknownGadString:
    DC.B    'U',0
    CNOP    0,2

FindTextGTags:
    DC.L    $00000000
    DC.L    $00000000
    DC.L    $8008002D,ReplaceStringGadString
    DC.L    $8008002E,256
    DC.L    $00000000
    DC.L    $8008002D,FindStringGadString
    DC.L    $8008002E,256
    DC.L    $00000000


ReplaceStringGadString:
    DC.B    '0',0
    CNOP    0,2

FindStringGadString:
    DC.B    '0',0
    CNOP    0,2

PPOKButtonText:
    DC.B    'OK',0

PPCancelButtonText:
    DC.B    'Cancel',0

PPNLQCheckText:
    DC.B    'Draft print:',0

PPProportionalCheckText:
    DC.B    'Proportional spacing:',0

PPDoubleSpaceCheckText:
    DC.B    'Double line spacing:',0

PPTopMarginStrText:
    DC.B    'Top margin:',0

PPBottomMarginStrText:
    DC.B    'Bottom margin:',0

PPPageLengthStrText:
    DC.B    'Page length:',0

PPLeftMarginStrText:
    DC.B    'Left margin:',0

PPRightMarginStrText:
    DC.B    'Right margin:',0

PPPageWidthStrText:
    DC.B    'Page width:',0

PPPrintToStrText:
    DC.B    'Print destinaton:',0

PPNumCopiesStrText:
    DC.B    'Number of copies:',0

    CNOP    0,2

ColoursTextGadText:
    DC.B    'Text colour:',0

ColoursFieldGadText:
    DC.B    'Field colour:',0

ColoursOKGadText:
    DC.B    'OK',0

ColoursCancelGadText:
    DC.B    'Cancel',0

    CNOP    0,2

FuncKeysOKGadText:
    DC.B    'OK',0

FuncKeysCancelGadText:
    DC.B    'Cancel',0

FuncKeysF1GadText:
    DC.B    'F1:',0

FuncKeysF2GadText:
    DC.B    'F2:',0

FuncKeysF3GadText:
    DC.B    'F3:',0

FuncKeysF4GadText:
    DC.B    'F4:',0

FuncKeysF5GadText:
    DC.B    'F5:',0

FuncKeysF6GadText:
    DC.B    'F6:',0

FuncKeysF7GadText:
    DC.B    'F7:',0

FuncKeysF8GadText:
    DC.B    'F8:',0

FuncKeysF9GadText:
    DC.B    'F9:',0

FuncKeysF10GadText:
    DC.B    'F10:',0

    CNOP    0,2

PrintedPercentageCancelText:
    DC.B    'Cancel',0

PrintedPercentageNumText:
    DC.B    '% Printed:',0

    CNOP    0,2

SpellSuggestionsGadText:
    DC.B    'Suggestions:',0

SpellReplaceGadText:
    DC.B    'Replace with:',0

SpellUnknownGadText:
    DC.B    'Unknown:',0

SpellCheckIgnoreGadText:
    DC.B    'Ignore',0

SpellCheckCancelGadText:
    DC.B    'Cancel',0

SpellCheckLearnGadText:
    DC.B    'Learn',0

SpellCheckReplaceGadText:
    DC.B    'Replace',0

    CNOP    0,2

FindOKGadText:
    DC.B    'OK',0

FindCancelGadText:
    DC.B    'Cancel',0

ReplaceStringGadText:
    DC.B    'Replace with:',0

FindStringGadText:
    DC.B    'Find:',0

    CNOP    0,2

    XDEF    MainEditWindowWindowTags

MainEditWindowWindowTags:
    DC.L    $80000093,1
MainEditWindowL:
    DC.L    $80000064,0
MainEditWindowT:
    DC.L    $80000065,0
MainEditWindowW:
    DC.L    $80000066,0
MainEditWindowH:
    DC.L    $80000067,0
    DC.L    $8000006A,$0040037E
    DC.L    $8000006B,$0000123F
    DC.L    $8000006E,MainEditWindowWTitle
    DC.L    $8000006F,MainEditWindowSTitle
    DC.L    $80000072,92
    DC.L    $80000073,65
    DC.L    $80000074,640
    DC.L    $80000075,256
    DC.L    $00000000

MainEditWindowWTitle:
    DC.B    'Untitled',0
    CNOP    0,2

MainEditWindowSTitle:
    DC.B    'TextEngine V5.2, Copyright © Nicholas Harvey 1991-2010.',0
    CNOP    0,2

    XDEF    PrinterPrefsWindowTags

PrinterPrefsWindowTags:
PrinterPrefsL:
    DC.L    $80000064,0
PrinterPrefsT:
    DC.L    $80000065,0
PrinterPrefsW:
    DC.L    $80000066,0
PrinterPrefsH:
    DC.L    $80000067,0
    DC.L    $8000006A,$00000264
    DC.L    $8000006B,$0000100E
PrinterPrefsWG:
    DC.L    $8000006C,0
    DC.L    $8000006E,PrinterPrefsWTitle
    DC.L    $8000006F,PrinterPrefsSTitle
    DC.L    $80000090,1
    DC.L    $00000000

PrinterPrefsWTitle:
    DC.B    'Printer preferences',0
    CNOP    0,2

PrinterPrefsSTitle:
    DC.B    'TextEngine V5.2, Copyright © Nicholas Harvey 1991-2010.',0
    CNOP    0,2

    XDEF    ColoursWindowTags

ColoursWindowTags:
ColoursL:
    DC.L    $80000064,0
ColoursT:
    DC.L    $80000065,0
ColoursW:
    DC.L    $80000066,0
ColoursH:
    DC.L    $80000067,0
    DC.L    $8000006A,$00000244
    DC.L    $8000006B,$0000100E
ColoursWG:
    DC.L    $8000006C,0
    DC.L    $8000006E,ColoursWTitle
    DC.L    $8000006F,ColoursSTitle
    DC.L    $00000000

ColoursWTitle:
    DC.B    'Colours',0
    CNOP    0,2

ColoursSTitle:
    DC.B    'TextEngine V5.2, Copyright © Nicholas Harvey 1991-2010.',0
    CNOP    0,2

    XDEF    FunctionKeysWindowTags

FunctionKeysWindowTags:
FunctionKeysL:
    DC.L    $80000064,0
FunctionKeysT:
    DC.L    $80000065,0
FunctionKeysW:
    DC.L    $80000066,0
FunctionKeysH:
    DC.L    $80000067,0
    DC.L    $8000006A,$00000244
    DC.L    $8000006B,$0000100E
FunctionKeysWG:
    DC.L    $8000006C,0
    DC.L    $8000006E,FunctionKeysWTitle
    DC.L    $8000006F,FunctionKeysSTitle
    DC.L    $00000000

FunctionKeysWTitle:
    DC.B    'Function keys',0
    CNOP    0,2

FunctionKeysSTitle:
    DC.B    'TextEngine V5.2, Copyright © Nicholas Harvey 1991-2010.',0
    CNOP    0,2

    XDEF    PrintDocumentWindowTags

PrintDocumentWindowTags:
PrintDocumentL:
    DC.L    $80000064,0
PrintDocumentT:
    DC.L    $80000065,0
PrintDocumentW:
    DC.L    $80000066,0
PrintDocumentH:
    DC.L    $80000067,0
    DC.L    $8000006A,$00000244
    DC.L    $8000006B,$0000100E
PrintDocumentWG:
    DC.L    $8000006C,0
    DC.L    $8000006E,PrintDocumentWTitle
    DC.L    $8000006F,PrintDocumentSTitle
    DC.L    $00000000

PrintDocumentWTitle:
    DC.B    'Printing...',0
    CNOP    0,2

PrintDocumentSTitle:
    DC.B    'TextEngine V5.2, Copyright © Nicholas Harvey 1991-2010.',0
    CNOP    0,2

    XDEF    SpellCheckerWindowTags

SpellCheckerWindowTags:
SpellCheckerL:
    DC.L    $80000064,0
SpellCheckerT:
    DC.L    $80000065,0
SpellCheckerW:
    DC.L    $80000066,0
SpellCheckerH:
    DC.L    $80000067,0
    DC.L    $8000006A,$0040027C
    DC.L    $8000006B,$0000100E
SpellCheckerWG:
    DC.L    $8000006C,0
    DC.L    $8000006E,SpellCheckerWTitle
    DC.L    $8000006F,SpellCheckerSTitle
    DC.L    $00000000

SpellCheckerWTitle:
    DC.B    'Spelling checker',0
    CNOP    0,2

SpellCheckerSTitle:
    DC.B    'TextEngine V5.2, Copyright © Nicholas Harvey 1991-2010.',0
    CNOP    0,2

    XDEF    FindTextWindowTags

FindTextWindowTags:
FindTextL:
    DC.L    $80000064,0
FindTextT:
    DC.L    $80000065,0
FindTextW:
    DC.L    $80000066,0
FindTextH:
    DC.L    $80000067,0
    DC.L    $8000006A,$00000244
    DC.L    $8000006B,$0000100E
FindTextWG:
    DC.L    $8000006C,0
    DC.L    $8000006E,FindTextWTitle
    DC.L    $8000006F,FindTextSTitle
    DC.L    $00000000

FindTextWTitle:
    DC.B    'Find text',0
    CNOP    0,2

FindTextSTitle:
    DC.B    'TextEngine V5.2, Copyright © Nicholas Harvey 1991-2010.',0
    CNOP    0,2

    XDEF    MainEditWindowNewMenu0

MainEditWindowNewMenu0:
    DC.B    1,0
    DC.L    MainEditWindowMName0
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu1:
    DC.B    2,0
    DC.L    MainEditWindowMName1
    DC.L    MainEditWindowMComm1
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu2:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu3:
    DC.B    2,0
    DC.L    MainEditWindowMName3
    DC.L    MainEditWindowMComm3
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu4:
    DC.B    2,0
    DC.L    MainEditWindowMName4
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu5:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu6:
    DC.B    2,0
    DC.L    MainEditWindowMName6
    DC.L    MainEditWindowMComm6
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu7:
    DC.B    2,0
    DC.L    MainEditWindowMName7
    DC.L    MainEditWindowMComm7
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu8:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu9:
    DC.B    2,0
    DC.L    MainEditWindowMName9
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu10:
    DC.B    2,0
    DC.L    MainEditWindowMName10
    DC.L    MainEditWindowMComm10
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu11:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu12:
    DC.B    2,0
    DC.L    MainEditWindowMName12
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu13:
    DC.B    3,0
    DC.L    MainEditWindowMName13
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu14:
    DC.B    3,0
    DC.L    MainEditWindowMName14
    DC.L    MainEditWindowMComm14
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu15:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu16:
    DC.B    2,0
    DC.L    MainEditWindowMName16
    DC.L    MainEditWindowMComm16
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu17:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu18:
    DC.B    2,0
    DC.L    MainEditWindowMName18
    DC.L    MainEditWindowMComm18
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu19:
    DC.B    1,0
    DC.L    MainEditWindowMName19
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu20:
    DC.B    2,0
    DC.L    MainEditWindowMName20
    DC.L    MainEditWindowMComm20
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu21:
    DC.B    2,0
    DC.L    MainEditWindowMName21
    DC.L    MainEditWindowMComm21
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu22:
    DC.B    2,0
    DC.L    MainEditWindowMName22
    DC.L    MainEditWindowMComm22
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu23:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu24:
    DC.B    2,0
    DC.L    MainEditWindowMName24
    DC.L    MainEditWindowMComm24
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu25:
    DC.B    2,0
    DC.L    MainEditWindowMName25
    DC.L    MainEditWindowMComm25
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu26:
    DC.B    2,0
    DC.L    MainEditWindowMName26
    DC.L    MainEditWindowMComm26
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu27:
    DC.B    2,0
    DC.L    MainEditWindowMName27
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu28:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu29:
    DC.B    2,0
    DC.L    MainEditWindowMName29
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu30:
    DC.B    1,0
    DC.L    MainEditWindowMName30
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu31:
    DC.B    2,0
    DC.L    MainEditWindowMName31
    DC.L    MainEditWindowMComm31
    DC.W    0
    DC.L    1,0

MainEditWindowNewMenu32:
    DC.B    2,0
    DC.L    MainEditWindowMName32
    DC.L    MainEditWindowMComm32
    DC.W    0
    DC.L    1,0

MainEditWindowNewMenu33:
    DC.B    2,0
    DC.L    MainEditWindowMName33
    DC.L    MainEditWindowMComm33
    DC.W    0
    DC.L    1,0

MainEditWindowNewMenu34:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu35:
    DC.B    2,0
    DC.L    MainEditWindowMName35
    DC.L    0
    DC.W    0
    DC.L    1,0

MainEditWindowNewMenu36:
    DC.B    2,0
    DC.L    MainEditWindowMName36
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu37:
    DC.B    2,0
    DC.L    MainEditWindowMName37
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu38:
    DC.B    2,0
    DC.L    MainEditWindowMName38
    DC.L    0
    DC.W    0
    DC.L    1,0

MainEditWindowNewMenu39:
    DC.B    2,0
    DC.L    MainEditWindowMName39
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu40:
    DC.B    2,0
    DC.L    MainEditWindowMName40
    DC.L    0
    DC.W    0
    DC.L    513,0

MainEditWindowNewMenu41:
    DC.B    2,0
    DC.L    MainEditWindowMName41
    DC.L    0
    DC.W    0
    DC.L    257,0

MainEditWindowNewMenu42:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu43:
    DC.B    2,0
    DC.L    MainEditWindowMName43
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu44:
    DC.B    1,0
    DC.L    MainEditWindowMName44
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu45:
    DC.B    2,0
    DC.L    MainEditWindowMName45
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu46:
    DC.B    2,0
    DC.L    MainEditWindowMName46
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu47:
    DC.B    2,0
    DC.L    MainEditWindowMName47
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu48:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu49:
    DC.B    2,0
    DC.L    MainEditWindowMName49
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu50:
    DC.B    1,0
    DC.L    MainEditWindowMName50
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu51:
    DC.B    2,0
    DC.L    MainEditWindowMName51
    DC.L    MainEditWindowMComm51
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu52:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu53:
    DC.B    2,0
    DC.L    MainEditWindowMName53
    DC.L    MainEditWindowMComm53
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu54:
    DC.B    2,0
    DC.L    MainEditWindowMName54
    DC.L    MainEditWindowMComm54
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu55:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu56:
    DC.B    2,0
    DC.L    MainEditWindowMName56
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu57:
    DC.B    2,0
    DC.L    MainEditWindowMName57
    DC.L    MainEditWindowMComm57
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu58:
    DC.B    1,0
    DC.L    MainEditWindowMName58
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu59:
    DC.B    2,0
    DC.L    MainEditWindowMName59
    DC.L    MainEditWindowMComm59
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu60:
    DC.B    2,0
    DC.L    MainEditWindowMName60
    DC.L    0
    DC.W    $0010
    DC.L    0,0

MainEditWindowNewMenu61:
    DC.B    2,0
    DC.L    MainEditWindowMName61
    DC.L    0
    DC.W    $0010
    DC.L    0,0

MainEditWindowNewMenu62:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu63:
    DC.B    2,0
    DC.L    MainEditWindowMName63
    DC.L    MainEditWindowMComm63
    DC.W    $0010
    DC.L    0,0

MainEditWindowNewMenu64:
    DC.B    1,0
    DC.L    MainEditWindowMName64
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu65:
    DC.B    2,0
    DC.L    MainEditWindowMName65
    DC.L    MainEditWindowMComm65
    DC.W    $0109
    DC.L    0,0

MainEditWindowNewMenu66:
    DC.B    2,0
    DC.L    MainEditWindowMName66
    DC.L    MainEditWindowMComm66
    DC.W    $0109
    DC.L    0,0

MainEditWindowNewMenu67:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu68:
    DC.B    2,0
    DC.L    MainEditWindowMName68
    DC.L    MainEditWindowMComm68
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu69:
    DC.B    2,0
    DC.L    MainEditWindowMName69
    DC.L    MainEditWindowMComm69
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu70:
    DC.B    2,0
    DC.L    MainEditWindowMName70
    DC.L    MainEditWindowMComm70
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu71:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu72:
    DC.B    2,0
    DC.L    MainEditWindowMName72
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu73:
    DC.B    1,0
    DC.L    MainEditWindowMName73
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu74:
    DC.B    2,0
    DC.L    MainEditWindowMName74
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu75:
    DC.B    2,0
    DC.L    MainEditWindowMName75
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu76:
    DC.B    2,0
    DC.L    MainEditWindowMName76
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu77:
    DC.B    2,0
    DC.L    MainEditWindowMName77
    DC.L    0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu78:
    DC.B    2,0
    DC.L    $FFFFFFFF,0
    DC.W    0
    DC.L    0,0

MainEditWindowNewMenu79:
    DC.B    2,0
    DC.L    MainEditWindowMName79
    DC.L    0
    DC.W    0
    DC.L    0,0

    DC.B    0,0
    DC.L    0,0
    DC.W    0
    DC.L    0,0

MainEditWindowMName0:
    DC.B    'Project',0

MainEditWindowMName1:
    DC.B    'New File...',0

MainEditWindowMComm1:
    DC.B    'N',0

MainEditWindowMName3:
    DC.B    'Open File...',0

MainEditWindowMComm3:
    DC.B    'O',0

MainEditWindowMName4:
    DC.B    'Insert File...',0

MainEditWindowMName6:
    DC.B    'Save File',0

MainEditWindowMComm6:
    DC.B    'S',0

MainEditWindowMName7:
    DC.B    'Save File As...',0

MainEditWindowMComm7:
    DC.B    'A',0

MainEditWindowMName9:
    DC.B    'Save ASCII File',0

MainEditWindowMName10:
    DC.B    'Save ASCII File As...',0

MainEditWindowMComm10:
    DC.B    'Y',0

MainEditWindowMName12:
    DC.B    'Print',0

MainEditWindowMName13:
    DC.B    'Preview',0

MainEditWindowMName14:
    DC.B    'Document...',0

MainEditWindowMComm14:
    DC.B    'P',0

MainEditWindowMName16:
    DC.B    'About TextEngine...',0

MainEditWindowMComm16:
    DC.B    '?',0

MainEditWindowMName18:
    DC.B    'Quit...',0

MainEditWindowMComm18:
    DC.B    'Q',0

MainEditWindowMName19:
    DC.B    'Edit',0

MainEditWindowMName20:
    DC.B    'Find...',0

MainEditWindowMComm20:
    DC.B    'F',0

MainEditWindowMName21:
    DC.B    'Find Again',0

MainEditWindowMComm21:
    DC.B    'G',0

MainEditWindowMName22:
    DC.B    'Replace',0

MainEditWindowMComm22:
    DC.B    'R',0

MainEditWindowMName24:
    DC.B    'Cut',0

MainEditWindowMComm24:
    DC.B    'X',0

MainEditWindowMName25:
    DC.B    'Copy',0

MainEditWindowMComm25:
    DC.B    'C',0

MainEditWindowMName26:
    DC.B    'Paste',0

MainEditWindowMComm26:
    DC.B    'V',0

MainEditWindowMName27:
    DC.B    'Delete',0

MainEditWindowMName29:
    DC.B    'Select All',0

MainEditWindowMName30:
    DC.B    'Format',0

MainEditWindowMName31:
    DC.B    'Bold',0

MainEditWindowMComm31:
    DC.B    'B',0

MainEditWindowMName32:
    DC.B    'Italic',0

MainEditWindowMComm32:
    DC.B    'I',0

MainEditWindowMName33:
    DC.B    'Underline',0

MainEditWindowMComm33:
    DC.B    'U',0

MainEditWindowMName35:
    DC.B    'Condensed',0

MainEditWindowMName36:
    DC.B    'Double Strike',0

MainEditWindowMName37:
    DC.B    'Elite',0

MainEditWindowMName38:
    DC.B    'Enlarged',0

MainEditWindowMName39:
    DC.B    'Pica',0

MainEditWindowMName40:
    DC.B    'Subscript',0

MainEditWindowMName41:
    DC.B    'Superscript',0

MainEditWindowMName43:
    DC.B    'Plain',0

MainEditWindowMName44:
    DC.B    'Align',0

MainEditWindowMName45:
    DC.B    'Left Justify',0

MainEditWindowMName46:
    DC.B    'Right Justify',0

MainEditWindowMName47:
    DC.B    'Centralise',0

MainEditWindowMName49:
    DC.B    'Flush Justify',0

MainEditWindowMName50:
    DC.B    'Tools',0

MainEditWindowMName51:
    DC.B    'Word Count...',0

MainEditWindowMComm51:
    DC.B    'W',0

MainEditWindowMName53:
    DC.B    'Go To Top Of File',0

MainEditWindowMComm53:
    DC.B    'T',0

MainEditWindowMName54:
    DC.B    'Go To End Of File',0

MainEditWindowMComm54:
    DC.B    'E',0

MainEditWindowMName56:
    DC.B    'Insert Bookmark',0

MainEditWindowMName57:
    DC.B    'Go To Next Bookmark',0

MainEditWindowMComm57:
    DC.B    '@',0

MainEditWindowMName58:
    DC.B    'Spelling',0

MainEditWindowMName59:
    DC.B    'Open Dictionary',0

MainEditWindowMComm59:
    DC.B    'D',0

MainEditWindowMName60:
    DC.B    'Close Dictionary',0

MainEditWindowMName61:
    DC.B    'Update Dictionary',0

MainEditWindowMName63:
    DC.B    'Check Document...',0

MainEditWindowMComm63:
    DC.B    'J',0

MainEditWindowMName64:
    DC.B    'Settings',0

MainEditWindowMName65:
    DC.B    'Word Wrap',0

MainEditWindowMComm65:
    DC.B    'L',0

MainEditWindowMName66:
    DC.B    'Show Borders',0

MainEditWindowMComm66:
    DC.B    'H',0

MainEditWindowMName68:
    DC.B    'Printer...',0

MainEditWindowMComm68:
    DC.B    'Z',0

MainEditWindowMName69:
    DC.B    'Function Keys...',0

MainEditWindowMComm69:
    DC.B    'K',0

MainEditWindowMName70:
    DC.B    'Colours...',0

MainEditWindowMComm70:
    DC.B    'M',0

MainEditWindowMName72:
    DC.B    'Save Settings',0

MainEditWindowMName73:
    DC.B    'External',0

MainEditWindowMName74:
    DC.B    'New Shell...',0

MainEditWindowMName75:
    DC.B    'Calculator...',0

MainEditWindowMName76:
    DC.B    'Multiview...',0

MainEditWindowMName77:
    DC.B    'Printer Prefs...',0

MainEditWindowMName79:
    DC.B    'New TextEngine...',0

    CNOP    0,2

ComputeX:
    move.l  d1,-(sp)
    move.w  FontX,d1
    bra.s   ComputeItX
ComputeY:
    move.l  d1,-(sp)
    move.w  FontY,d1
    mulu    d1,d0
    addq.w  #4,d0
    divu    #8,d0
    move.l  (sp)+,d1
    rts

ComputeItX:
    mulu    d1,d0
    addq.w  #4,d0
    divu    #8,d0
    move.l  (sp)+,d1
    rts

ComputeFont:
    lea.l   Attr,a0
    move.l  a0,Font
    move.l  Scr,a1
    lea.l   84(a1),a1
    move.l  52(a1),a1
    move.l  10(a1),(a0)
    move.w  20(a1),4(a0)
    move.w  24(a1),FontX
    move.w  20(a1),FontY
    move.l  Scr,a0
    move.b  36(a0),d0
    ext.w   d0
    move.w  d0,OffX
    move.l  40(a0),a1
    move.w  4(a1),d0
    addq.w  #1,d0
    add.b   35(a0),d0
    move.w  d0,OffY
    tst.w   d2
    beq.s   CompDone
    tst.w   d3
    beq.s   CompDone
    move.w  d2,d0
    bsr     ComputeX
    add.w   OffX,d0
    add.b   37(a0),d0
    cmp.w   12(a0),d0
    bhi.s   UseTopaz
    move.w  d3,d0
    bsr     ComputeY
    add.w   OffY,d0
    add.b   38(a0),d0
    cmp.w   14(a0),d0
    bhi.s   UseTopaz
CompDone:
    rts
UseTopaz:
    move.l  Font,a0
    move.l  #TopazName,(a0)
    move.w  #8,FontY
    move.w  #8,FontX
    move.w  #8,4(a0)
    rts

    XDEF    SetupScreen

SetupScreen
    movem.l d1-d3/a0-a2/a6,-(sp)
    move.l  _IntuitionBase,a6
    move.l  PubScreenName,a0
    jsr     LockPubScreen(a6)
    move.l  d0,Scr
    tst.l   d0
    beq     SError
    moveq   #0,d2
    moveq   #0,d3
    bsr     ComputeFont
    move.l  Scr,a0
    move.l  _GadToolsBase,a6
    lea.l   TD,a1
    jsr     GetVisualInfoA(a6)
    move.l  d0,VisualInfo
    tst.l   d0
    beq     VError
    moveq   #0,d0
SDone:
    movem.l (sp)+,d1-d3/a0-a2/a6
    rts
SError:
    moveq   #1,d0
    bra.s   SDone
VError:
    moveq   #2,d0
    bra.s   SDone

    XDEF    CloseDownScreen

CloseDownScreen:
    movem.l d0-d1/a0-a1/a6,-(sp)
    move.l  _GadToolsBase,a6
    move.l  VisualInfo,a0
    cmpa.l  #0,a0
    beq.s   NoVis
    jsr     FreeVisualInfo(a6)
    move.l  #0,VisualInfo
NoVis:
    move.l  _IntuitionBase,a6
    suba.l  a0,a0
    move.l  Scr,a1
    cmpa.l  #0,a1
    beq.s   NoScr
    jsr     UnlockPubScreen(a6)
    move.l  #0,Scr
NoScr:
    movem.l (sp)+,d0-d1/a0-a1/a6
    rts

    XDEF    OpenMainEditWindowWindow

OpenMainEditWindowWindow:
    movem.l d1-d4/a0-a4/a6,-(sp)
    move.l  Scr,a0
    moveq   #0,d3
    moveq   #0,d2
    move.w  MainEditWindowWidth,d2
    move.w  MainEditWindowHeight,d3
    bsr     ComputeFont
    move.l  Scr,a0
    move.l  d2,d0
    bsr     ComputeX
    move.l  d0,d4
    move.w  MainEditWindowLeft,d2
    add.w   d2,d0
    add.w   OffX,d0
    add.b   37(a0),d0
    cmp.w   12(a0),d0
    bls.s   MainEditWindowWOk
    move.w  12(a0),d0
    sub.w   d4,d0
    move.w  d0,d2
MainEditWindowWOk:
    move.l  d3,d0
    bsr     ComputeY
    move.l  d0,d4
    move.w  MainEditWindowTop,d3
    add.w   d3,d0
    add.w   OffY,d0
    add.b   38(a0),d0
    cmp.w   14(a0),d0
    bls.s   MainEditWindowHOk
    move.w  14(a0),d0
    sub.w   d4,d0
    move.w  d0,d3
MainEditWindowHOk:
    move.l  _GadToolsBase,a6
    lea.l   MainEditWindowNewMenu0,a0
    lea.l   MTags0,a1
    jsr     CreateMenusA(a6)
    move.l  d0,MainEditWindowMenus
    tst.l   d0
    beq     MainEditWindowMError
    move.l  d0,a0
    move.l  VisualInfo,a1
    lea.l   MTags1,a2
    jsr     LayoutMenusA(a6)
    ext.l   d2
    ext.l   d3
    move.l  d2,MainEditWindowL+4
    move.l  d3,MainEditWindowT+4
    move.l  Scr,a0
    move.w  MainEditWindowWidth,d0
    bsr     ComputeX
    add.w   OffX,d0
    add.b   37(a0),d0
    move.l  d0,MainEditWindowW+4
    move.w  MainEditWindowHeight,d0
    bsr     ComputeY
    add.w   OffY,d0
    add.b   38(a0),d0
    move.l  d0,MainEditWindowH+4
    move.l  _IntuitionBase,a6
    suba.l  a0,a0
    lea.l   MainEditWindowWindowTags,a1
    jsr     OpenWindowTagList(a6)
    move.l  d0,MainEditWindowWnd
    tst.l   d0
    beq     MainEditWindowWError
    move.l   MainEditWindowWnd,a0
    move.l   MainEditWindowMenus,a1
    jsr      SetMenuStrip(a6)
    move.l  _GadToolsBase,a6
    move.l  MainEditWindowWnd,a0
    suba.l  a1,a1
    jsr     GT_RefreshWindow(a6)
    moveq   #0,d0
MainEditWindowDone:
    movem.l (sp)+,d1-d4/a0-a4/a6
    rts
MainEditWindowMError:
    moveq   #3,d0
    bra.s   MainEditWindowDone
MainEditWindowWError:
    moveq   #4,d0
    bra.s   MainEditWindowDone

    XDEF    CloseMainEditWindowWindow

CloseMainEditWindowWindow:
    movem.l d0-d1/a0-a2/a6,-(sp)
    move.l   _IntuitionBase,a6
    move.l   MainEditWindowMenus,a0
    cmpa.l   #0,a0
    beq      MainEditWindowNMenu
    move.l   MainEditWindowWnd,a0
    jsr      ClearMenuStrip(a6)
    move.l   _GadToolsBase,a6
    move.l   MainEditWindowMenus,a0
    jsr      FreeMenus(a6)
    move.l   #0,MainEditWindowMenus
MainEditWindowNMenu:
    move.l  _IntuitionBase,a6
    move.l  MainEditWindowWnd,a0
    cmpa.l  #0,a0
    beq     MainEditWindowNWnd
    jsr     CloseWindow(a6)
    move.l  #0,MainEditWindowWnd
MainEditWindowNWnd:
    movem.l (sp)+,d0-d1/a0-a2/a6
    rts

    XDEF    PrinterPrefsRender

PrinterPrefsRender:
    movem.l d0-d5/a0-a2/a6,-(sp)
    move.l  PrinterPrefsWnd,a0
    move.w  PrinterPrefsWidth,d2
    move.l  PrinterPrefsHeight,d3
    bsr     ComputeFont
    move.l  VisualInfo,NR+4
    move.l  VisualInfo,IR+4
    move.l  _GadToolsBase,a6
    move.l  PrinterPrefsWnd,a0
    move.l  50(a0),a2
    move.l  a2,a0
    lea.l   IR,a1
    move.l  #89,d0
    bsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #225,d0
    bsr     ComputeX
    move.l  d0,d2
    move.l  #21,d0
    bsr     ComputeY
    move.l  d0,d3
    move.l  #211,d0
    bsr     ComputeX
    add.w   OffX,d0
    jsr     DrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   IR,a1
    move.l  #4,d0
    bsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #225,d0
    bsr     ComputeX
    move.l  d0,d2
    move.l  #34,d0
    bsr     ComputeY
    move.l  d0,d3
    move.l  #211,d0
    bsr     ComputeX
    add.w   OffX,d0
    jsr     DrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   IR,a1
    move.l  #41,d0
    bsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #225,d0
    bsr     ComputeX
    move.l  d0,d2
    move.l  #45,d0
    bsr     ComputeY
    move.l  d0,d3
    move.l  #211,d0
    bsr     ComputeX
    add.w   OffX,d0
    jsr     DrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   IR,a1
    move.l  #4,d0
    bsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #197,d0
    bsr     ComputeX
    move.l  d0,d2
    move.l  #106,d0
    bsr     ComputeY
    move.l  d0,d3
    move.l  #8,d0
    bsr     ComputeX
    add.w   OffX,d0
    jsr     DrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   NR,a1
    move.l  #0,d0
    bsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #444,d0
    bsr     ComputeX
    move.l  d0,d2
    move.l  #129,d0
    bsr     ComputeY
    move.l  d0,d3
    move.l  #0,d0
    bsr     ComputeX
    add.w   OffX,d0
    jsr     DrawBevelBoxA(a6)
    movem.l (sp)+,d0-d5/a0-a2/a6
    rts

    XDEF    OpenPrinterPrefsWindow

OpenPrinterPrefsWindow:
    movem.l d1-d4/a0-a4/a6,-(sp)
    move.l  Scr,a0
    moveq   #0,d3
    moveq   #0,d2
    move.w  PrinterPrefsWidth,d2
    move.w  PrinterPrefsHeight,d3
    bsr     ComputeFont
    move.l  Scr,a0
    move.l  d2,d0
    bsr     ComputeX
    move.l  d0,d4
    move.w  PrinterPrefsLeft,d2
    add.w   d2,d0
    add.w   OffX,d0
    add.b   37(a0),d0
    cmp.w   12(a0),d0
    bls.s   PrinterPrefsWOk
    move.w  12(a0),d0
    sub.w   d4,d0
    move.w  d0,d2
PrinterPrefsWOk:
    move.l  d3,d0
    bsr     ComputeY
    move.l  d0,d4
    move.w  PrinterPrefsTop,d3
    add.w   d3,d0
    add.w   OffY,d0
    add.b   38(a0),d0
    cmp.w   14(a0),d0
    bls.s   PrinterPrefsHOk
    move.w  14(a0),d0
    sub.w   d4,d0
    move.w  d0,d3
PrinterPrefsHOk:
    move.l  _GadToolsBase,a6
    lea.l   PrinterPrefsGList,a0
    jsr     CreateContext(a6)
    move.l  d0,a3
    tst.l   d0
    beq     PrinterPrefsCError
    movem.w d2-d3,-(sp)
    moveq   #0,d3
    lea.l   PrinterPrefsGTags,a4
PrinterPrefsGL:
    move.l  _SysBase,a6
    lea.l   PrinterPrefsNGads,a0
    move.l  d3,d0
    mulu    #30,d0
    add.l   d0,a0
    lea.l   BufNewGad,a1
    moveq   #30,d0
    jsr     CopyMem(a6)
    lea.l   BufNewGad,a0
    move.l  VisualInfo,22(a0)
    move.l  Font,12(a0)
    move.w  (a0),d0
    bsr     ComputeX
    add.w   OffX,d0
    move.w  d0,(a0)
    move.w  2(a0),d0
    bsr     ComputeY
    add.w   OffY,d0
    move.w  d0,2(a0)
    move.w  4(a0),d0
    bsr     ComputeX
    move.w  d0,4(a0)
    move.w  6(a0),d0
    bsr     ComputeY
    move.w  d0,6(a0)
    move.l  _GadToolsBase,a6
    lea.l   PrinterPrefsGTypes,a0
    moveq   #0,d0
    move.l  d3,d1
    asl.l   #1,d1
    add.l   d1,a0
    move.w  (a0),d0
    move.l  a3,a0
    lea.l   BufNewGad,a1
    move.l  a4,a2
    jsr     CreateGadgetA(a6)
    tst.l   d0
    bne.s    PrinterPrefsCOK
    movem.w (sp)+,d2-d3
    bra     PrinterPrefsCError
PrinterPrefsCOK:
    move.l  d0,a3
    move.l  d3,d0
    asl.l   #2,d0
    lea.l   PrinterPrefsGadgets,a0
    add.l   d0,a0
    move.l  a3,(a0)
PrinterPrefsTL:
    tst.l   (a4)
    beq.s   PrinterPrefsDN
    addq.w  #8,a4
    bra.s   PrinterPrefsTL
PrinterPrefsDN:
    addq.w  #4,a4
    addq.w  #1,d3
    cmp.w   #PrinterPrefs_CNT,d3
    bmi     PrinterPrefsGL
    movem.w (sp)+,d2-d3
    move.l  PrinterPrefsGList,PrinterPrefsWG+4
    ext.l   d2
    ext.l   d3
    move.l  d2,PrinterPrefsL+4
    move.l  d3,PrinterPrefsT+4
    move.l  Scr,a0
    move.w  PrinterPrefsWidth,d0
    bsr     ComputeX
    add.w   OffX,d0
    add.b   37(a0),d0
    move.l  d0,PrinterPrefsW+4
    move.w  PrinterPrefsHeight,d0
    bsr     ComputeY
    add.w   OffY,d0
    add.b   38(a0),d0
    move.l  d0,PrinterPrefsH+4
    move.l  _IntuitionBase,a6
    suba.l  a0,a0
    lea.l   PrinterPrefsWindowTags,a1
    jsr     OpenWindowTagList(a6)
    move.l  d0,PrinterPrefsWnd
    tst.l   d0
    beq     PrinterPrefsWError
    move.l  _GadToolsBase,a6
    move.l  PrinterPrefsWnd,a0
    suba.l  a1,a1
    jsr     GT_RefreshWindow(a6)
    bsr     PrinterPrefsRender
    moveq   #0,d0
PrinterPrefsDone:
    movem.l (sp)+,d1-d4/a0-a4/a6
    rts
PrinterPrefsCError:
    moveq   #1,d0
    bra.s   PrinterPrefsDone
PrinterPrefsGError:
    moveq   #2,d0
    bra.s   PrinterPrefsDone
PrinterPrefsWError:
    moveq   #4,d0
    bra.s   PrinterPrefsDone

    XDEF    ClosePrinterPrefsWindow

ClosePrinterPrefsWindow:
    movem.l d0-d1/a0-a2/a6,-(sp)
    move.l  _IntuitionBase,a6
    move.l  PrinterPrefsWnd,a0
    cmpa.l  #0,a0
    beq     PrinterPrefsNWnd
    jsr     CloseWindow(a6)
    move.l  #0,PrinterPrefsWnd
PrinterPrefsNWnd:
    move.l  _GadToolsBase,a6
    move.l  PrinterPrefsGList,a0
    cmpa.l  #0,a0
    beq     PrinterPrefsNGad
    jsr     FreeGadgets(a6)
    move.l  #0,PrinterPrefsGList
PrinterPrefsNGad:
    movem.l (sp)+,d0-d1/a0-a2/a6
    rts

    XDEF    ColoursRender

ColoursRender:
    movem.l d0-d5/a0-a2/a6,-(sp)
    move.l  ColoursWnd,a0
    move.w  ColoursWidth,d2
    move.l  ColoursHeight,d3
    bsr     ComputeFont
    move.l  VisualInfo,NR+4
    move.l  VisualInfo,IR+4
    move.l  _GadToolsBase,a6
    move.l  ColoursWnd,a0
    move.l  50(a0),a2
    move.l  a2,a0
    lea.l   IR,a1
    move.l  #4,d0
    bsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #185,d0
    bsr     ComputeX
    move.l  d0,d2
    move.l  #61,d0
    bsr     ComputeY
    move.l  d0,d3
    move.l  #8,d0
    bsr     ComputeX
    add.w   OffX,d0
    jsr     DrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   IR,a1
    move.l  #4,d0
    bsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #185,d0
    bsr     ComputeX
    move.l  d0,d2
    move.l  #61,d0
    bsr     ComputeY
    move.l  d0,d3
    move.l  #199,d0
    bsr     ComputeX
    add.w   OffX,d0
    jsr     DrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   NR,a1
    move.l  #0,d0
    bsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #392,d0
    bsr     ComputeX
    move.l  d0,d2
    move.l  #84,d0
    bsr     ComputeY
    move.l  d0,d3
    move.l  #0,d0
    bsr     ComputeX
    add.w   OffX,d0
    jsr     DrawBevelBoxA(a6)
    movem.l (sp)+,d0-d5/a0-a2/a6
    rts

    XDEF    OpenColoursWindow

OpenColoursWindow:
    movem.l d1-d4/a0-a4/a6,-(sp)
    move.l  Scr,a0
    moveq   #0,d3
    moveq   #0,d2
    move.w  ColoursWidth,d2
    move.w  ColoursHeight,d3
    bsr     ComputeFont
    move.l  Scr,a0
    move.l  d2,d0
    bsr     ComputeX
    move.l  d0,d4
    move.w  ColoursLeft,d2
    add.w   d2,d0
    add.w   OffX,d0
    add.b   37(a0),d0
    cmp.w   12(a0),d0
    bls.s   ColoursWOk
    move.w  12(a0),d0
    sub.w   d4,d0
    move.w  d0,d2
ColoursWOk:
    move.l  d3,d0
    bsr     ComputeY
    move.l  d0,d4
    move.w  ColoursTop,d3
    add.w   d3,d0
    add.w   OffY,d0
    add.b   38(a0),d0
    cmp.w   14(a0),d0
    bls.s   ColoursHOk
    move.w  14(a0),d0
    sub.w   d4,d0
    move.w  d0,d3
ColoursHOk:
    move.l  _GadToolsBase,a6
    lea.l   ColoursGList,a0
    jsr     CreateContext(a6)
    move.l  d0,a3
    tst.l   d0
    beq     ColoursCError
    movem.w d2-d3,-(sp)
    moveq   #0,d3
    lea.l   ColoursGTags,a4
ColoursGL:
    move.l  _SysBase,a6
    lea.l   ColoursNGads,a0
    move.l  d3,d0
    mulu    #30,d0
    add.l   d0,a0
    lea.l   BufNewGad,a1
    moveq   #30,d0
    jsr     CopyMem(a6)
    lea.l   BufNewGad,a0
    move.l  VisualInfo,22(a0)
    move.l  Font,12(a0)
    move.w  (a0),d0
    bsr     ComputeX
    add.w   OffX,d0
    move.w  d0,(a0)
    move.w  2(a0),d0
    bsr     ComputeY
    add.w   OffY,d0
    move.w  d0,2(a0)
    move.w  4(a0),d0
    bsr     ComputeX
    move.w  d0,4(a0)
    move.w  6(a0),d0
    bsr     ComputeY
    move.w  d0,6(a0)
    move.l  _GadToolsBase,a6
    lea.l   ColoursGTypes,a0
    moveq   #0,d0
    move.l  d3,d1
    asl.l   #1,d1
    add.l   d1,a0
    move.w  (a0),d0
    move.l  a3,a0
    lea.l   BufNewGad,a1
    move.l  a4,a2
    jsr     CreateGadgetA(a6)
    tst.l   d0
    bne.s    ColoursCOK
    movem.w (sp)+,d2-d3
    bra     ColoursCError
ColoursCOK:
    move.l  d0,a3
    move.l  d3,d0
    asl.l   #2,d0
    lea.l   ColoursGadgets,a0
    add.l   d0,a0
    move.l  a3,(a0)
ColoursTL:
    tst.l   (a4)
    beq.s   ColoursDN
    addq.w  #8,a4
    bra.s   ColoursTL
ColoursDN:
    addq.w  #4,a4
    addq.w  #1,d3
    cmp.w   #Colours_CNT,d3
    bmi     ColoursGL
    movem.w (sp)+,d2-d3
    move.l  ColoursGList,ColoursWG+4
    ext.l   d2
    ext.l   d3
    move.l  d2,ColoursL+4
    move.l  d3,ColoursT+4
    move.l  Scr,a0
    move.w  ColoursWidth,d0
    bsr     ComputeX
    add.w   OffX,d0
    add.b   37(a0),d0
    move.l  d0,ColoursW+4
    move.w  ColoursHeight,d0
    bsr     ComputeY
    add.w   OffY,d0
    add.b   38(a0),d0
    move.l  d0,ColoursH+4
    move.l  _IntuitionBase,a6
    suba.l  a0,a0
    lea.l   ColoursWindowTags,a1
    jsr     OpenWindowTagList(a6)
    move.l  d0,ColoursWnd
    tst.l   d0
    beq     ColoursWError
    move.l  _GadToolsBase,a6
    move.l  ColoursWnd,a0
    suba.l  a1,a1
    jsr     GT_RefreshWindow(a6)
    bsr     ColoursRender
    moveq   #0,d0
ColoursDone:
    movem.l (sp)+,d1-d4/a0-a4/a6
    rts
ColoursCError:
    moveq   #1,d0
    bra.s   ColoursDone
ColoursGError:
    moveq   #2,d0
    bra.s   ColoursDone
ColoursWError:
    moveq   #4,d0
    bra.s   ColoursDone

    XDEF    CloseColoursWindow

CloseColoursWindow:
    movem.l d0-d1/a0-a2/a6,-(sp)
    move.l  _IntuitionBase,a6
    move.l  ColoursWnd,a0
    cmpa.l  #0,a0
    beq     ColoursNWnd
    jsr     CloseWindow(a6)
    move.l  #0,ColoursWnd
ColoursNWnd:
    move.l  _GadToolsBase,a6
    move.l  ColoursGList,a0
    cmpa.l  #0,a0
    beq     ColoursNGad
    jsr     FreeGadgets(a6)
    move.l  #0,ColoursGList
ColoursNGad:
    movem.l (sp)+,d0-d1/a0-a2/a6
    rts

    XDEF    FunctionKeysRender

FunctionKeysRender:
    movem.l d0-d5/a0-a2/a6,-(sp)
    move.l  FunctionKeysWnd,a0
    move.w  FunctionKeysWidth,d2
    move.l  FunctionKeysHeight,d3
    bsr     ComputeFont
    move.l  VisualInfo,NR+4
    move.l  VisualInfo,IR+4
    move.l  _GadToolsBase,a6
    move.l  FunctionKeysWnd,a0
    move.l  50(a0),a2
    move.l  a2,a0
    lea.l   IR,a1
    move.l  #4,d0
    bsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #297,d0
    bsr     ComputeX
    move.l  d0,d2
    move.l  #173,d0
    bsr     ComputeY
    move.l  d0,d3
    move.l  #8,d0
    bsr     ComputeX
    add.w   OffX,d0
    jsr     DrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   NR,a1
    move.l  #0,d0
    bsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #313,d0
    bsr     ComputeX
    move.l  d0,d2
    move.l  #196,d0
    bsr     ComputeY
    move.l  d0,d3
    move.l  #0,d0
    bsr     ComputeX
    add.w   OffX,d0
    jsr     DrawBevelBoxA(a6)
    movem.l (sp)+,d0-d5/a0-a2/a6
    rts

    XDEF    OpenFunctionKeysWindow

OpenFunctionKeysWindow:
    movem.l d1-d4/a0-a4/a6,-(sp)
    move.l  Scr,a0
    moveq   #0,d3
    moveq   #0,d2
    move.w  FunctionKeysWidth,d2
    move.w  FunctionKeysHeight,d3
    bsr     ComputeFont
    move.l  Scr,a0
    move.l  d2,d0
    bsr     ComputeX
    move.l  d0,d4
    move.w  FunctionKeysLeft,d2
    add.w   d2,d0
    add.w   OffX,d0
    add.b   37(a0),d0
    cmp.w   12(a0),d0
    bls.s   FunctionKeysWOk
    move.w  12(a0),d0
    sub.w   d4,d0
    move.w  d0,d2
FunctionKeysWOk:
    move.l  d3,d0
    bsr     ComputeY
    move.l  d0,d4
    move.w  FunctionKeysTop,d3
    add.w   d3,d0
    add.w   OffY,d0
    add.b   38(a0),d0
    cmp.w   14(a0),d0
    bls.s   FunctionKeysHOk
    move.w  14(a0),d0
    sub.w   d4,d0
    move.w  d0,d3
FunctionKeysHOk:
    move.l  _GadToolsBase,a6
    lea.l   FunctionKeysGList,a0
    jsr     CreateContext(a6)
    move.l  d0,a3
    tst.l   d0
    beq     FunctionKeysCError
    movem.w d2-d3,-(sp)
    moveq   #0,d3
    lea.l   FunctionKeysGTags,a4
FunctionKeysGL:
    move.l  _SysBase,a6
    lea.l   FunctionKeysNGads,a0
    move.l  d3,d0
    mulu    #30,d0
    add.l   d0,a0
    lea.l   BufNewGad,a1
    moveq   #30,d0
    jsr     CopyMem(a6)
    lea.l   BufNewGad,a0
    move.l  VisualInfo,22(a0)
    move.l  Font,12(a0)
    move.w  (a0),d0
    bsr     ComputeX
    add.w   OffX,d0
    move.w  d0,(a0)
    move.w  2(a0),d0
    bsr     ComputeY
    add.w   OffY,d0
    move.w  d0,2(a0)
    move.w  4(a0),d0
    bsr     ComputeX
    move.w  d0,4(a0)
    move.w  6(a0),d0
    bsr     ComputeY
    move.w  d0,6(a0)
    move.l  _GadToolsBase,a6
    lea.l   FunctionKeysGTypes,a0
    moveq   #0,d0
    move.l  d3,d1
    asl.l   #1,d1
    add.l   d1,a0
    move.w  (a0),d0
    move.l  a3,a0
    lea.l   BufNewGad,a1
    move.l  a4,a2
    jsr     CreateGadgetA(a6)
    tst.l   d0
    bne.s    FunctionKeysCOK
    movem.w (sp)+,d2-d3
    bra     FunctionKeysCError
FunctionKeysCOK:
    move.l  d0,a3
    move.l  d3,d0
    asl.l   #2,d0
    lea.l   FunctionKeysGadgets,a0
    add.l   d0,a0
    move.l  a3,(a0)
FunctionKeysTL:
    tst.l   (a4)
    beq.s   FunctionKeysDN
    addq.w  #8,a4
    bra.s   FunctionKeysTL
FunctionKeysDN:
    addq.w  #4,a4
    addq.w  #1,d3
    cmp.w   #FunctionKeys_CNT,d3
    bmi     FunctionKeysGL
    movem.w (sp)+,d2-d3
    move.l  FunctionKeysGList,FunctionKeysWG+4
    ext.l   d2
    ext.l   d3
    move.l  d2,FunctionKeysL+4
    move.l  d3,FunctionKeysT+4
    move.l  Scr,a0
    move.w  FunctionKeysWidth,d0
    bsr     ComputeX
    add.w   OffX,d0
    add.b   37(a0),d0
    move.l  d0,FunctionKeysW+4
    move.w  FunctionKeysHeight,d0
    bsr     ComputeY
    add.w   OffY,d0
    add.b   38(a0),d0
    move.l  d0,FunctionKeysH+4
    move.l  _IntuitionBase,a6
    suba.l  a0,a0
    lea.l   FunctionKeysWindowTags,a1
    jsr     OpenWindowTagList(a6)
    move.l  d0,FunctionKeysWnd
    tst.l   d0
    beq     FunctionKeysWError
    move.l  _GadToolsBase,a6
    move.l  FunctionKeysWnd,a0
    suba.l  a1,a1
    jsr     GT_RefreshWindow(a6)
    bsr     FunctionKeysRender
    moveq   #0,d0
FunctionKeysDone:
    movem.l (sp)+,d1-d4/a0-a4/a6
    rts
FunctionKeysCError:
    moveq   #1,d0
    bra.s   FunctionKeysDone
FunctionKeysGError:
    moveq   #2,d0
    bra.s   FunctionKeysDone
FunctionKeysWError:
    moveq   #4,d0
    bra.s   FunctionKeysDone

    XDEF    CloseFunctionKeysWindow

CloseFunctionKeysWindow:
    movem.l d0-d1/a0-a2/a6,-(sp)
    move.l  _IntuitionBase,a6
    move.l  FunctionKeysWnd,a0
    cmpa.l  #0,a0
    beq     FunctionKeysNWnd
    jsr     CloseWindow(a6)
    move.l  #0,FunctionKeysWnd
FunctionKeysNWnd:
    move.l  _GadToolsBase,a6
    move.l  FunctionKeysGList,a0
    cmpa.l  #0,a0
    beq     FunctionKeysNGad
    jsr     FreeGadgets(a6)
    move.l  #0,FunctionKeysGList
FunctionKeysNGad:
    movem.l (sp)+,d0-d1/a0-a2/a6
    rts

    XDEF    PrintDocumentRender

PrintDocumentRender:
    movem.l d0-d5/a0-a2/a6,-(sp)
    move.l  PrintDocumentWnd,a0
    move.w  PrintDocumentWidth,d2
    move.l  PrintDocumentHeight,d3
    bsr     ComputeFont
    move.l  VisualInfo,NR+4
    move.l  VisualInfo,IR+4
    move.l  _GadToolsBase,a6
    move.l  PrintDocumentWnd,a0
    move.l  50(a0),a2
    move.l  a2,a0
    lea.l   IR,a1
    move.l  #4,d0
    bsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #149,d0
    bsr     ComputeX
    move.l  d0,d2
    move.l  #25,d0
    bsr     ComputeY
    move.l  d0,d3
    move.l  #8,d0
    bsr     ComputeX
    add.w   OffX,d0
    jsr     DrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   NR,a1
    move.l  #0,d0
    bsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #165,d0
    bsr     ComputeX
    move.l  d0,d2
    move.l  #48,d0
    bsr     ComputeY
    move.l  d0,d3
    move.l  #0,d0
    bsr     ComputeX
    add.w   OffX,d0
    jsr     DrawBevelBoxA(a6)
    movem.l (sp)+,d0-d5/a0-a2/a6
    rts

    XDEF    OpenPrintDocumentWindow

OpenPrintDocumentWindow:
    movem.l d1-d4/a0-a4/a6,-(sp)
    move.l  Scr,a0
    moveq   #0,d3
    moveq   #0,d2
    move.w  PrintDocumentWidth,d2
    move.w  PrintDocumentHeight,d3
    bsr     ComputeFont
    move.l  Scr,a0
    move.l  d2,d0
    bsr     ComputeX
    move.l  d0,d4
    move.w  PrintDocumentLeft,d2
    add.w   d2,d0
    add.w   OffX,d0
    add.b   37(a0),d0
    cmp.w   12(a0),d0
    bls.s   PrintDocumentWOk
    move.w  12(a0),d0
    sub.w   d4,d0
    move.w  d0,d2
PrintDocumentWOk:
    move.l  d3,d0
    bsr     ComputeY
    move.l  d0,d4
    move.w  PrintDocumentTop,d3
    add.w   d3,d0
    add.w   OffY,d0
    add.b   38(a0),d0
    cmp.w   14(a0),d0
    bls.s   PrintDocumentHOk
    move.w  14(a0),d0
    sub.w   d4,d0
    move.w  d0,d3
PrintDocumentHOk:
    move.l  _GadToolsBase,a6
    lea.l   PrintDocumentGList,a0
    jsr     CreateContext(a6)
    move.l  d0,a3
    tst.l   d0
    beq     PrintDocumentCError
    movem.w d2-d3,-(sp)
    moveq   #0,d3
    lea.l   PrintDocumentGTags,a4
PrintDocumentGL:
    move.l  _SysBase,a6
    lea.l   PrintDocumentNGads,a0
    move.l  d3,d0
    mulu    #30,d0
    add.l   d0,a0
    lea.l   BufNewGad,a1
    moveq   #30,d0
    jsr     CopyMem(a6)
    lea.l   BufNewGad,a0
    move.l  VisualInfo,22(a0)
    move.l  Font,12(a0)
    move.w  (a0),d0
    bsr     ComputeX
    add.w   OffX,d0
    move.w  d0,(a0)
    move.w  2(a0),d0
    bsr     ComputeY
    add.w   OffY,d0
    move.w  d0,2(a0)
    move.w  4(a0),d0
    bsr     ComputeX
    move.w  d0,4(a0)
    move.w  6(a0),d0
    bsr     ComputeY
    move.w  d0,6(a0)
    move.l  _GadToolsBase,a6
    lea.l   PrintDocumentGTypes,a0
    moveq   #0,d0
    move.l  d3,d1
    asl.l   #1,d1
    add.l   d1,a0
    move.w  (a0),d0
    move.l  a3,a0
    lea.l   BufNewGad,a1
    move.l  a4,a2
    jsr     CreateGadgetA(a6)
    tst.l   d0
    bne.s    PrintDocumentCOK
    movem.w (sp)+,d2-d3
    bra     PrintDocumentCError
PrintDocumentCOK:
    move.l  d0,a3
    move.l  d3,d0
    asl.l   #2,d0
    lea.l   PrintDocumentGadgets,a0
    add.l   d0,a0
    move.l  a3,(a0)
PrintDocumentTL:
    tst.l   (a4)
    beq.s   PrintDocumentDN
    addq.w  #8,a4
    bra.s   PrintDocumentTL
PrintDocumentDN:
    addq.w  #4,a4
    addq.w  #1,d3
    cmp.w   #PrintDocument_CNT,d3
    bmi     PrintDocumentGL
    movem.w (sp)+,d2-d3
    move.l  PrintDocumentGList,PrintDocumentWG+4
    ext.l   d2
    ext.l   d3
    move.l  d2,PrintDocumentL+4
    move.l  d3,PrintDocumentT+4
    move.l  Scr,a0
    move.w  PrintDocumentWidth,d0
    bsr     ComputeX
    add.w   OffX,d0
    add.b   37(a0),d0
    move.l  d0,PrintDocumentW+4
    move.w  PrintDocumentHeight,d0
    bsr     ComputeY
    add.w   OffY,d0
    add.b   38(a0),d0
    move.l  d0,PrintDocumentH+4
    move.l  _IntuitionBase,a6
    suba.l  a0,a0
    lea.l   PrintDocumentWindowTags,a1
    jsr     OpenWindowTagList(a6)
    move.l  d0,PrintDocumentWnd
    tst.l   d0
    beq     PrintDocumentWError
    move.l  _GadToolsBase,a6
    move.l  PrintDocumentWnd,a0
    suba.l  a1,a1
    jsr     GT_RefreshWindow(a6)
    bsr     PrintDocumentRender
    moveq   #0,d0
PrintDocumentDone:
    movem.l (sp)+,d1-d4/a0-a4/a6
    rts
PrintDocumentCError:
    moveq   #1,d0
    bra.s   PrintDocumentDone
PrintDocumentGError:
    moveq   #2,d0
    bra.s   PrintDocumentDone
PrintDocumentWError:
    moveq   #4,d0
    bra.s   PrintDocumentDone

    XDEF    ClosePrintDocumentWindow

ClosePrintDocumentWindow:
    movem.l d0-d1/a0-a2/a6,-(sp)
    move.l  _IntuitionBase,a6
    move.l  PrintDocumentWnd,a0
    cmpa.l  #0,a0
    beq     PrintDocumentNWnd
    jsr     CloseWindow(a6)
    move.l  #0,PrintDocumentWnd
PrintDocumentNWnd:
    move.l  _GadToolsBase,a6
    move.l  PrintDocumentGList,a0
    cmpa.l  #0,a0
    beq     PrintDocumentNGad
    jsr     FreeGadgets(a6)
    move.l  #0,PrintDocumentGList
PrintDocumentNGad:
    movem.l (sp)+,d0-d1/a0-a2/a6
    rts

    XDEF    SpellCheckerRender

SpellCheckerRender:
    movem.l d0-d5/a0-a2/a6,-(sp)
    move.l  SpellCheckerWnd,a0
    move.w  SpellCheckerWidth,d2
    move.l  SpellCheckerHeight,d3
    bsr     ComputeFont
    move.l  VisualInfo,NR+4
    move.l  VisualInfo,IR+4
    move.l  _GadToolsBase,a6
    move.l  SpellCheckerWnd,a0
    move.l  50(a0),a2
    move.l  a2,a0
    lea.l   IR,a1
    move.l  #4,d0
    bsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #313,d0
    bsr     ComputeX
    move.l  d0,d2
    move.l  #108,d0
    bsr     ComputeY
    move.l  d0,d3
    move.l  #8,d0
    bsr     ComputeX
    add.w   OffX,d0
    jsr     DrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   NR,a1
    move.l  #0,d0
    bsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #329,d0
    bsr     ComputeX
    move.l  d0,d2
    move.l  #131,d0
    bsr     ComputeY
    move.l  d0,d3
    move.l  #0,d0
    bsr     ComputeX
    add.w   OffX,d0
    jsr     DrawBevelBoxA(a6)
    movem.l (sp)+,d0-d5/a0-a2/a6
    rts

    XDEF    OpenSpellCheckerWindow

OpenSpellCheckerWindow:
    movem.l d1-d4/a0-a4/a6,-(sp)
    move.l  Scr,a0
    moveq   #0,d3
    moveq   #0,d2
    move.w  SpellCheckerWidth,d2
    move.w  SpellCheckerHeight,d3
    bsr     ComputeFont
    move.l  Scr,a0
    move.l  d2,d0
    bsr     ComputeX
    move.l  d0,d4
    move.w  SpellCheckerLeft,d2
    add.w   d2,d0
    add.w   OffX,d0
    add.b   37(a0),d0
    cmp.w   12(a0),d0
    bls.s   SpellCheckerWOk
    move.w  12(a0),d0
    sub.w   d4,d0
    move.w  d0,d2
SpellCheckerWOk:
    move.l  d3,d0
    bsr     ComputeY
    move.l  d0,d4
    move.w  SpellCheckerTop,d3
    add.w   d3,d0
    add.w   OffY,d0
    add.b   38(a0),d0
    cmp.w   14(a0),d0
    bls.s   SpellCheckerHOk
    move.w  14(a0),d0
    sub.w   d4,d0
    move.w  d0,d3
SpellCheckerHOk:
    move.l  _GadToolsBase,a6
    lea.l   SpellCheckerGList,a0
    jsr     CreateContext(a6)
    move.l  d0,a3
    tst.l   d0
    beq     SpellCheckerCError
    movem.w d2-d3,-(sp)
    moveq   #0,d3
    lea.l   SpellCheckerGTags,a4
SpellCheckerGL:
    move.l  _SysBase,a6
    lea.l   SpellCheckerNGads,a0
    move.l  d3,d0
    mulu    #30,d0
    add.l   d0,a0
    lea.l   BufNewGad,a1
    moveq   #30,d0
    jsr     CopyMem(a6)
    lea.l   BufNewGad,a0
    move.l  VisualInfo,22(a0)
    move.l  Font,12(a0)
    move.w  (a0),d0
    bsr     ComputeX
    add.w   OffX,d0
    move.w  d0,(a0)
    move.w  2(a0),d0
    bsr     ComputeY
    add.w   OffY,d0
    move.w  d0,2(a0)
    move.w  4(a0),d0
    bsr     ComputeX
    move.w  d0,4(a0)
    move.w  6(a0),d0
    bsr     ComputeY
    move.w  d0,6(a0)
    move.l  _GadToolsBase,a6
    lea.l   SpellCheckerGTypes,a0
    moveq   #0,d0
    move.l  d3,d1
    asl.l   #1,d1
    add.l   d1,a0
    move.w  (a0),d0
    move.l  a3,a0
    lea.l   BufNewGad,a1
    move.l  a4,a2
    jsr     CreateGadgetA(a6)
    tst.l   d0
    bne.s    SpellCheckerCOK
    movem.w (sp)+,d2-d3
    bra     SpellCheckerCError
SpellCheckerCOK:
    move.l  d0,a3
    move.l  d3,d0
    asl.l   #2,d0
    lea.l   SpellCheckerGadgets,a0
    add.l   d0,a0
    move.l  a3,(a0)
SpellCheckerTL:
    tst.l   (a4)
    beq.s   SpellCheckerDN
    addq.w  #8,a4
    bra.s   SpellCheckerTL
SpellCheckerDN:
    addq.w  #4,a4
    addq.w  #1,d3
    cmp.w   #SpellChecker_CNT,d3
    bmi     SpellCheckerGL
    movem.w (sp)+,d2-d3
    move.l  SpellCheckerGList,SpellCheckerWG+4
    ext.l   d2
    ext.l   d3
    move.l  d2,SpellCheckerL+4
    move.l  d3,SpellCheckerT+4
    move.l  Scr,a0
    move.w  SpellCheckerWidth,d0
    bsr     ComputeX
    add.w   OffX,d0
    add.b   37(a0),d0
    move.l  d0,SpellCheckerW+4
    move.w  SpellCheckerHeight,d0
    bsr     ComputeY
    add.w   OffY,d0
    add.b   38(a0),d0
    move.l  d0,SpellCheckerH+4
    move.l  _IntuitionBase,a6
    suba.l  a0,a0
    lea.l   SpellCheckerWindowTags,a1
    jsr     OpenWindowTagList(a6)
    move.l  d0,SpellCheckerWnd
    tst.l   d0
    beq     SpellCheckerWError
    move.l  _GadToolsBase,a6
    move.l  SpellCheckerWnd,a0
    suba.l  a1,a1
    jsr     GT_RefreshWindow(a6)
    bsr     SpellCheckerRender
    moveq   #0,d0
SpellCheckerDone:
    movem.l (sp)+,d1-d4/a0-a4/a6
    rts
SpellCheckerCError:
    moveq   #1,d0
    bra.s   SpellCheckerDone
SpellCheckerGError:
    moveq   #2,d0
    bra.s   SpellCheckerDone
SpellCheckerWError:
    moveq   #4,d0
    bra.s   SpellCheckerDone

    XDEF    CloseSpellCheckerWindow

CloseSpellCheckerWindow:
    movem.l d0-d1/a0-a2/a6,-(sp)
    move.l  _IntuitionBase,a6
    move.l  SpellCheckerWnd,a0
    cmpa.l  #0,a0
    beq     SpellCheckerNWnd
    jsr     CloseWindow(a6)
    move.l  #0,SpellCheckerWnd
SpellCheckerNWnd:
    move.l  _GadToolsBase,a6
    move.l  SpellCheckerGList,a0
    cmpa.l  #0,a0
    beq     SpellCheckerNGad
    jsr     FreeGadgets(a6)
    move.l  #0,SpellCheckerGList
SpellCheckerNGad:
    movem.l (sp)+,d0-d1/a0-a2/a6
    rts

    XDEF    FindTextRender

FindTextRender:
    movem.l d0-d5/a0-a2/a6,-(sp)
    move.l  FindTextWnd,a0
    move.w  FindTextWidth,d2
    move.l  FindTextHeight,d3
    bsr     ComputeFont
    move.l  VisualInfo,NR+4
    move.l  VisualInfo,IR+4
    move.l  _GadToolsBase,a6
    move.l  FindTextWnd,a0
    move.l  50(a0),a2
    move.l  a2,a0
    lea.l   IR,a1
    move.l  #4,d0
    bsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #365,d0
    bsr     ComputeX
    move.l  d0,d2
    move.l  #46,d0
    bsr     ComputeY
    move.l  d0,d3
    move.l  #8,d0
    bsr     ComputeX
    add.w   OffX,d0
    jsr     DrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   NR,a1
    move.l  #0,d0
    bsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #381,d0
    bsr     ComputeX
    move.l  d0,d2
    move.l  #69,d0
    bsr     ComputeY
    move.l  d0,d3
    move.l  #0,d0
    bsr     ComputeX
    add.w   OffX,d0
    jsr     DrawBevelBoxA(a6)
    movem.l (sp)+,d0-d5/a0-a2/a6
    rts

    XDEF    OpenFindTextWindow

OpenFindTextWindow:
    movem.l d1-d4/a0-a4/a6,-(sp)
    move.l  Scr,a0
    moveq   #0,d3
    moveq   #0,d2
    move.w  FindTextWidth,d2
    move.w  FindTextHeight,d3
    bsr     ComputeFont
    move.l  Scr,a0
    move.l  d2,d0
    bsr     ComputeX
    move.l  d0,d4
    move.w  FindTextLeft,d2
    add.w   d2,d0
    add.w   OffX,d0
    add.b   37(a0),d0
    cmp.w   12(a0),d0
    bls.s   FindTextWOk
    move.w  12(a0),d0
    sub.w   d4,d0
    move.w  d0,d2
FindTextWOk:
    move.l  d3,d0
    bsr     ComputeY
    move.l  d0,d4
    move.w  FindTextTop,d3
    add.w   d3,d0
    add.w   OffY,d0
    add.b   38(a0),d0
    cmp.w   14(a0),d0
    bls.s   FindTextHOk
    move.w  14(a0),d0
    sub.w   d4,d0
    move.w  d0,d3
FindTextHOk:
    move.l  _GadToolsBase,a6
    lea.l   FindTextGList,a0
    jsr     CreateContext(a6)
    move.l  d0,a3
    tst.l   d0
    beq     FindTextCError
    movem.w d2-d3,-(sp)
    moveq   #0,d3
    lea.l   FindTextGTags,a4
FindTextGL:
    move.l  _SysBase,a6
    lea.l   FindTextNGads,a0
    move.l  d3,d0
    mulu    #30,d0
    add.l   d0,a0
    lea.l   BufNewGad,a1
    moveq   #30,d0
    jsr     CopyMem(a6)
    lea.l   BufNewGad,a0
    move.l  VisualInfo,22(a0)
    move.l  Font,12(a0)
    move.w  (a0),d0
    bsr     ComputeX
    add.w   OffX,d0
    move.w  d0,(a0)
    move.w  2(a0),d0
    bsr     ComputeY
    add.w   OffY,d0
    move.w  d0,2(a0)
    move.w  4(a0),d0
    bsr     ComputeX
    move.w  d0,4(a0)
    move.w  6(a0),d0
    bsr     ComputeY
    move.w  d0,6(a0)
    move.l  _GadToolsBase,a6
    lea.l   FindTextGTypes,a0
    moveq   #0,d0
    move.l  d3,d1
    asl.l   #1,d1
    add.l   d1,a0
    move.w  (a0),d0
    move.l  a3,a0
    lea.l   BufNewGad,a1
    move.l  a4,a2
    jsr     CreateGadgetA(a6)
    tst.l   d0
    bne.s    FindTextCOK
    movem.w (sp)+,d2-d3
    bra     FindTextCError
FindTextCOK:
    move.l  d0,a3
    move.l  d3,d0
    asl.l   #2,d0
    lea.l   FindTextGadgets,a0
    add.l   d0,a0
    move.l  a3,(a0)
FindTextTL:
    tst.l   (a4)
    beq.s   FindTextDN
    addq.w  #8,a4
    bra.s   FindTextTL
FindTextDN:
    addq.w  #4,a4
    addq.w  #1,d3
    cmp.w   #FindText_CNT,d3
    bmi     FindTextGL
    movem.w (sp)+,d2-d3
    move.l  FindTextGList,FindTextWG+4
    ext.l   d2
    ext.l   d3
    move.l  d2,FindTextL+4
    move.l  d3,FindTextT+4
    move.l  Scr,a0
    move.w  FindTextWidth,d0
    bsr     ComputeX
    add.w   OffX,d0
    add.b   37(a0),d0
    move.l  d0,FindTextW+4
    move.w  FindTextHeight,d0
    bsr     ComputeY
    add.w   OffY,d0
    add.b   38(a0),d0
    move.l  d0,FindTextH+4
    move.l  _IntuitionBase,a6
    suba.l  a0,a0
    lea.l   FindTextWindowTags,a1
    jsr     OpenWindowTagList(a6)
    move.l  d0,FindTextWnd
    tst.l   d0
    beq     FindTextWError
    move.l  _GadToolsBase,a6
    move.l  FindTextWnd,a0
    suba.l  a1,a1
    jsr     GT_RefreshWindow(a6)
    bsr     FindTextRender
    moveq   #0,d0
FindTextDone:
    movem.l (sp)+,d1-d4/a0-a4/a6
    rts
FindTextCError:
    moveq   #1,d0
    bra.s   FindTextDone
FindTextGError:
    moveq   #2,d0
    bra.s   FindTextDone
FindTextWError:
    moveq   #4,d0
    bra.s   FindTextDone

    XDEF    CloseFindTextWindow

CloseFindTextWindow:
    movem.l d0-d1/a0-a2/a6,-(sp)
    move.l  _IntuitionBase,a6
    move.l  FindTextWnd,a0
    cmpa.l  #0,a0
    beq     FindTextNWnd
    jsr     CloseWindow(a6)
    move.l  #0,FindTextWnd
FindTextNWnd:
    move.l  _GadToolsBase,a6
    move.l  FindTextGList,a0
    cmpa.l  #0,a0
    beq     FindTextNGad
    jsr     FreeGadgets(a6)
    move.l  #0,FindTextGList
FindTextNGad:
    movem.l (sp)+,d0-d1/a0-a2/a6
    rts

